/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package gui;

import data.BinaryTree;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;

/**
 *
 * @author CyK
 */
public class JFrmProyectoUI extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrmProyectoUI
     */
    public JFrmProyectoUI() {
        initComponents();
        JListActividades.setModel(listModel);
        JSpnPrioridad.setModel(numModel);
        JSpnPrioridad.getEditor().setBackground(Color.DARK_GRAY);
        tree = new BinaryTree();
    }
    
    private String nodeToString(String act, int prioridad){
        return act + " | Prioridad: " + Integer.toString(prioridad);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JSpnPrioridad = new javax.swing.JSpinner();
        JTxtFActividad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JBtnAgregar = new javax.swing.JButton();
        JBtnEliminar = new javax.swing.JButton();
        JBtnOrdenar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListActividades = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Organizador de tareas");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Organizador de Actividades");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actividad");
        jLabel1.setName("JlblActividad"); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prioridad");
        jLabel2.setName("JlblPrioridad"); // NOI18N

        JSpnPrioridad.setBackground(Color.black);
        JSpnPrioridad.setModel(numModel);
        JSpnPrioridad.setName("JSpnPrioridad"); // NOI18N

        JTxtFActividad.setBackground(new java.awt.Color(67, 67, 67));
        JTxtFActividad.setForeground(new java.awt.Color(255, 255, 255));
        JTxtFActividad.setName("JTxtFActividad"); // NOI18N

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Nota: la prioridad 5 es la mínima");

        JBtnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        JBtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        JBtnAgregar.setText("Agregar");
        JBtnAgregar.setName("JBtnAgregar"); // NOI18N
        JBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAgregarActionPerformed(evt);
            }
        });

        JBtnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        JBtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        JBtnEliminar.setText("Eliminar");
        JBtnEliminar.setName("JBtnEliminar"); // NOI18N
        JBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEliminarActionPerformed(evt);
            }
        });

        JBtnOrdenar.setBackground(new java.awt.Color(0, 0, 0));
        JBtnOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        JBtnOrdenar.setText("Ordenar");
        JBtnOrdenar.setName("JBtnOrdenar"); // NOI18N
        JBtnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnOrdenarActionPerformed(evt);
            }
        });

        JListActividades.setBackground(new java.awt.Color(67, 67, 67));
        JListActividades.setForeground(new java.awt.Color(255, 255, 255));
        JListActividades.setModel(listModel);
        JListActividades.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JListActividades.setName("JListActividades"); // NOI18N
        JListActividades.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JListActividadesFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(JListActividades);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JSpnPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JTxtFActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(133, 133, 133)
                                            .addComponent(jLabel1))))))
                        .addGap(18, 36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBtnAgregar)
                            .addComponent(JBtnOrdenar)
                            .addComponent(JBtnEliminar))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtFActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSpnPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnAgregar))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(JBtnOrdenar)
                        .addGap(55, 55, 55)
                        .addComponent(JBtnEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAgregarActionPerformed
        String actividad = JTxtFActividad.getText();
        Integer prioridad = (Integer) JSpnPrioridad.getValue();
        int insert = tree.insert(actividad, prioridad);
        if(insert == 1){
            listModel.addElement(nodeToString(actividad.trim(), prioridad));
            JTxtFActividad.setText("");
        }else if(insert == 0){
            JOptionPane.showMessageDialog(null, "No se puede insertar actividades nulas. "
                    + "Por favor, complete el campo.", "Error inserción", JOptionPane.WARNING_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "No se puede insertar actividades repetidas",
                    "Error inserción", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBtnAgregarActionPerformed

    private void JBtnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnOrdenarActionPerformed
        listModel.clear();
        for(String node : tree.inOrder()) {
            listModel.addElement(node);
        }
    }//GEN-LAST:event_JBtnOrdenarActionPerformed

    private void JBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEliminarActionPerformed
        try{
            String Originalvalue = JListActividades.getSelectedValue();
            String [] values = Originalvalue.split("\\|");
            String valueAct = values[0].trim();
            int valuePrio = Integer.parseInt(String.valueOf(values[1].trim().charAt(11)));
            System.out.println(valueAct + " PRIO " + valuePrio);
            if(tree.deleteNode(valueAct, valuePrio)) {
                listModel.removeElement(Originalvalue);
            }else{
                JOptionPane.showMessageDialog(null, "Ha sucedido un error al eliminar el ítem "
                        + "seleccionado. Por favor, contacte al administrador.", "Error interno",
                        JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error. Se debe seleccionar algún ítem. ", 
                    "Error eliminación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBtnEliminarActionPerformed

    private void JListActividadesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JListActividadesFocusGained
        
    }//GEN-LAST:event_JListActividadesFocusGained
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmProyectoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmProyectoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmProyectoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmProyectoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmProyectoUI().setVisible(true);
            }
        });
    }
    private DefaultListModel<String> listModel = new DefaultListModel<>();
    SpinnerNumberModel numModel = new SpinnerNumberModel(5, 1, 5, 1);
    private BinaryTree tree;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAgregar;
    private javax.swing.JButton JBtnEliminar;
    private javax.swing.JButton JBtnOrdenar;
    private javax.swing.JList<String> JListActividades;
    private javax.swing.JSpinner JSpnPrioridad;
    private javax.swing.JTextField JTxtFActividad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
